In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Employee_Attrition.csv")

In [3]:
df.shape

(1000, 10)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         1000 non-null   str
 1   Age                 1000 non-null   int64
 2   Gender              1000 non-null   str
 3   Department          1000 non-null   str
 4   Experience_Years    1000 non-null   int64
 5   Monthly_Salary      1000 non-null   int64
 6   Performance_Rating  1000 non-null   int64
 7   Work_Life_Balance   1000 non-null   str
 8   Job_Satisfaction    1000 non-null   int64
 9   Attrition_Status    1000 non-null   str
dtypes: int64(5), str(5)
memory usage: 78.3 KB

In [5]:
df.sample(5)

,Employee_ID,Age,Gender,Department,Experience_Years,Monthly_Salary,Performance_Rating,Work_Life_Balance,Job_Satisfaction,Attrition_Status
449,E1450,44,Male,Support,24,143001,3,Average,7,No
462,E1463,56,Female,Data Science,18,137306,3,Good,3,No
77,E1078,44,Male,Support,15,159206,1,Poor,6,No
76,E1077,27,Male,Testing,17,47637,4,Good,4,No
944,E1945,51,Female,DevOps,11,119607,2,Good,7,No

Assignment Questions

Question-1

In [6]:
Total_Attritiion = df[df['Attrition_Status']== 'Yes'].shape[0]

In [7]:
Total_Attritiion

284

In [8]:
Overall_Attrition = (Total_Attritiion/ df.shape[0])*100

In [9]:
print(f"Overall Attrition: {Overall_Attrition:.2f}%")

Overall Attrition: 28.40%

Question-2

In [10]:
dept = df.groupby('Department').agg(
    Total_Employees = ('Employee_ID', "count"),
    Attrition_per_dept = ('Attrition_Status', lambda x : (x == 'Yes').sum()))

dept['Attrition_per_dept']= ((dept['Attrition_per_dept']/dept['Total_Employees'])*100).round(2)
dept["Attrition_per_dept"] = dept["Attrition_per_dept"].apply(lambda x: f"{x:.2f}%")

In [11]:
dept

              Total_Employees Attrition_per_dept
Department
Data Science              132             25.76%
DevOps                    124             22.58%
HR                        130             34.62%
Marketing                 122             27.05%
Sales                     124             32.26%
Software                  117             35.04%
Support                   124             24.19%
Testing                   127             25.98%

In [12]:
# dept["Attrition_Rate"] = dept["Attrition_Rate"].map(lambda x: f"{x:.0f}%")
# Step by step:

# Take each value (12.0, 12.5, 16.0)

# Apply the lambda function: f"{x:.0f}%"

# :.0f → format as integer (no decimals)

# Add % at the end

In [13]:
dept = pd.DataFrame({"Attrition_per_dept": [12, 25, 8]})

In [14]:
dept

   Attrition_per_dept
0                  12
1                  25
2                   8

In [15]:
bins = [0, 25000, 50000, 75000, 100000, 125000, 150000, 175000, 200000]
labels = ["0-25K","25K-50K","50K-75K","75K-100K","100K-125K","125K-150K","150K-175K","175K-200K"]

df["Salary_Range"] = pd.cut(df["Monthly_Salary"], bins=bins, labels=labels, right=False)

In [16]:
summary = (
    df.groupby("Salary_Range")
      .agg(
          Total_Employees=("Employee_ID", "count"),
          Attrition_Yes=("Attrition_Status", lambda x: (x == "Yes").sum())
      )
)

# Calculate attrition rate (%)
summary["Attrition_Rate"] = (summary["Attrition_Yes"] / summary["Total_Employees"]) * 100

# Sort by attrition rate
# summary = summary.sort_values(by="Attrition_Rate", ascending=False).round(2)

summary["Attrition_Rate"] = summary["Attrition_Rate"].apply(lambda x: f"{x:.2f}%")

print(summary.sort_values(by="Attrition_Rate",ascending=False))

              Total_Employees  Attrition_Yes Attrition_Rate
Salary_Range
25K-50K                   134             46         34.33%
175K-200K                 156             47         30.13%
75K-100K                  138             40         28.99%
125K-150K                 130             36         27.69%
100K-125K                 146             40         27.40%
150K-175K                 136             35         25.74%
50K-75K                   160             40         25.00%

In [17]:
# import pandas as pd

# # Sample data
# dept = pd.DataFrame({"Attrition_per_dept": [12, 25, 8]})

# # Normal function
# def format_percentage(x):
#     return f"{x:.2f}%"

# # Apply function to column
# dept["Attrition_per_dept"] = dept["Attrition_per_dept"].apply(format_percentage)

# print(dept)

In [18]:
df.groupby('Department').agg( Avg_per_dept = ('Job_Satisfaction', 'mean')).round(2)

              Avg_per_dept
Department
Data Science          5.26
DevOps                5.85
HR                    5.38
Marketing             5.12
Sales                 5.34
Software              5.09
Support               5.78
Testing               5.84

In [19]:
df.head()

,Employee_ID,Age,Gender,Department,Experience_Years,Monthly_Salary,Performance_Rating,Work_Life_Balance,Job_Satisfaction,Attrition_Status,Salary_Range
0,E1001,50,Female,HR,4,177270,3,Average,7,No,175K-200K
1,E1002,43,Female,HR,5,174521,3,Poor,1,Yes,150K-175K
2,E1003,32,Male,DevOps,7,63163,5,Average,8,No,50K-75K
3,E1004,29,Female,HR,0,192028,1,Average,5,Yes,175K-200K
4,E1005,30,Male,DevOps,7,192827,4,Poor,6,Yes,175K-200K

In [20]:
df["Attrition"] = df["Attrition_Status"].map({"Yes": 1, "No": 0})

In [21]:
df.head()

,Employee_ID,Age,Gender,Department,Experience_Years,Monthly_Salary,Performance_Rating,Work_Life_Balance,Job_Satisfaction,Attrition_Status,Salary_Range,Attrition
0,E1001,50,Female,HR,4,177270,3,Average,7,No,175K-200K,0
1,E1002,43,Female,HR,5,174521,3,Poor,1,Yes,150K-175K,1
2,E1003,32,Male,DevOps,7,63163,5,Average,8,No,50K-75K,0
3,E1004,29,Female,HR,0,192028,1,Average,5,Yes,175K-200K,1
4,E1005,30,Male,DevOps,7,192827,4,Poor,6,Yes,175K-200K,1

In [22]:
# def to_flag(x):
#     return 1 if x == "Yes" else 0

# df["Attrition_Flag"] = df["Attrition_Status"].apply(to_flag)

In [23]:
correlation = df["Experience_Years"].corr(df["Attrition"]).round(3)
print("Correlation between Experience and Attrition:", correlation)

Correlation between Experience and Attrition: -0.032

In [24]:
df.groupby('Attrition_Status').agg(avg= ('Performance_Rating' , 'mean')).round(2)

                   avg
Attrition_Status
No                3.03
Yes               2.84

In [25]:
df.head()

,Employee_ID,Age,Gender,Department,Experience_Years,Monthly_Salary,Performance_Rating,Work_Life_Balance,Job_Satisfaction,Attrition_Status,Salary_Range,Attrition
0,E1001,50,Female,HR,4,177270,3,Average,7,No,175K-200K,0
1,E1002,43,Female,HR,5,174521,3,Poor,1,Yes,150K-175K,1
2,E1003,32,Male,DevOps,7,63163,5,Average,8,No,50K-75K,0
3,E1004,29,Female,HR,0,192028,1,Average,5,Yes,175K-200K,1
4,E1005,30,Male,DevOps,7,192827,4,Poor,6,Yes,175K-200K,1

In [26]:
df['Experience_Years'].corr(df['Attrition'])

np.float64(-0.0316579910488813)

In [27]:
ct =pd.crosstab(df['Department'],df['Attrition_Status'])

In [28]:
ct['Attrition_Rate (%)'] = round(ct['Yes'] / ct.sum(axis=1) * 100,2)

In [29]:
ct

Attrition_Status  No  Yes  Attrition_Rate (%)
Department
Data Science      98   34               25.76
DevOps            96   28               22.58
HR                85   45               34.62
Marketing         89   33               27.05
Sales             84   40               32.26
Software          76   41               35.04
Support           94   30               24.19
Testing           94   33               25.98

In [30]:
bins = [18, 25, 35, 45, 55, 65, 100]   # ranges
labels = ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels, right=False)

In [31]:
df.head()

,Employee_ID,Age,Gender,Department,Experience_Years,Monthly_Salary,Performance_Rating,Work_Life_Balance,Job_Satisfaction,Attrition_Status,Salary_Range,Attrition,Age_Group
0,E1001,50,Female,HR,4,177270,3,Average,7,No,175K-200K,0,45-54
1,E1002,43,Female,HR,5,174521,3,Poor,1,Yes,150K-175K,1,35-44
2,E1003,32,Male,DevOps,7,63163,5,Average,8,No,50K-75K,0,25-34
3,E1004,29,Female,HR,0,192028,1,Average,5,Yes,175K-200K,1,25-34
4,E1005,30,Male,DevOps,7,192827,4,Poor,6,Yes,175K-200K,1,25-34

In [32]:
summary = pd.pivot_table(
    df,
    index="Age_Group",
    values="Attrition_Status",
    aggfunc=lambda x: (x == "Yes").sum()
).sort_values(by="Attrition_Status", ascending=False)

print(summary)

# print(f{"The age_group between {summary.idxmax()} has the highest attiration"})
print("\n")
print(f"{summary['Attrition_Status'].idxmax()} age_group has the highest attrition")
print("Based on that i fell that in tha tage_group most employees are freshers and  having exprience of 3-5 years")
print("so i think they likely to chnage the comapany beacuse job shift incraesae there growth and salaries")

           Attrition_Status
Age_Group
25-34                    79
35-44                    70
45-54                    65
55-64                    37
18-24                    33


25-34 age_group has the highest attrition
Based on that i fell that in tha tage_group most employees are freshers and  having exprience of 3-5 years
so i think they likely to chnage the comapany beacuse job shift incraesae there growth and salaries

In [33]:
# always think that the values changes when we corect to percentage up and downs can happen
# always dont think high value and the highest percntage after groupby